name: Build, Deploy to Firebase, and Copy to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build the project
        run: npm run build

      - name: Check if dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist/ directory not found!"
            exit 1
          fi

      - name: Save Build Artifacts
        run: |
          mkdir -p ${{ github.workspace }}/dist_output
          cp -r ${{ github.workspace }}/dist/* ${{ github.workspace }}/dist_output/

      - name: Checkout GitHub Pages Repo
        uses: actions/checkout@v3
        with:
          repository: Dhruv7201/Dhruv7201.github.io
          token: ${{ secrets.GH_PAT }}

      - name: Copy Build Files to GitHub Pages Repo
        run: |
          rm -rf ./*
          cp -r ${{ github.workspace }}/dist_output/* .
          git add .
          git config --global user.email "dhruv.modi2345@gmail.com"
          git config --global user.name "Dhruv Modi"
          git commit -m "Deploy updated build from portfolio repo" || echo "No changes to commit"
          git push origin main
