name: Build, Deploy to Firebase, and Copy to GitHub Pages Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Portfolio Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build the project
        run: npm run build

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting

      - name: Save Build Artifacts
        run: |
          mkdir -p build_output
          cp -r build/* build_output/

      - name: Checkout GitHub Pages Repo
        uses: actions/checkout@v3
        with:
          repository: Dhruv7201/Dhruv7201.github.io
          token: ${{ secrets.GH_PAT }}  # Use a GitHub PAT stored as a secret

      - name: Copy Build Files to GitHub Pages Repo
        run: |
          rm -rf ./*
          cp -r ../build_output/* .
          git add .
          git config --global user.email "dhruv.modi2345@gmail.com"
          git config --global user.name "Dhruv Modi"
          git commit -m "Deploy updated build from portfolio repo" || echo "No changes to commit"
          git push origin main
